version: "3.7"

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-9

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9
    
    postgresql11:
        image: postgres:11.7
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            PGDATA: ${PG_DATA}
        volumes:
            - postgres:/data/postgres
            - pg-data:/var/lib/postgresql/data
        ports:
            - "5441:5432"
        networks:
            - laravel-9

    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel-9

    redis:
        image: redis:latest
        networks:
            - laravel-9

volumes:
    postgres:
    pg-data:

networks:
    laravel-9:
        driver: bridge
